name: releases

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y gcc libssl-dev

      - name: Install deps (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install openssl

      - name: Install Chocolatey + MinGW (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install -y mingw

      - name: Build (Linux & macOS)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p build
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            gcc -Wall -O2 src/*.c -Isrc/include \
              -I/opt/homebrew/opt/openssl/include \
              -L/opt/homebrew/opt/openssl/lib \
              -lcrypto -o build/lockr-macos
          else
            gcc -Wall -O2 src/*.c -Isrc/include -lcrypto -o build/lockr-linux
          fi

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          mkdir build
          & 'C:\ProgramData\chocolatey\bin\gcc.exe' -Wall -O2 src/*.c -Isrc/include -lcrypto -o build/lockr.exe

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lockr-${{ matrix.os }}
          path: |
            build/lockr*

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/**/lockr*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
