name: releases

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y gcc libssl-dev

      - name: Install deps (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install openssl

      - name: Setup MSYS2 on Windows
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-openssl

      - name: Build (Linux & macOS)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p build
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            gcc -Wall -O2 src/*.c -Isrc/include \
              -I/opt/homebrew/opt/openssl/include \
              -L/opt/homebrew/opt/openssl/lib \
              -lcrypto -o build/lockr-macos
          else
            gcc -Wall -O2 src/*.c -Isrc/include -lcrypto -o build/lockr-linux
          fi

      - name: Build (Windows with MSYS2 gcc)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          mkdir build
          gcc -Wall -O2 src/*.c -Isrc/include -lcrypto -o build/lockr.exe

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lockr-${{ matrix.os }}
          path: build/lockr*

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/**/lockr*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
